/** All tips shown in the tip-of-the-day system */
export const TIPS: ReadonlyArray<{ title: string; body: string; command?: string; keybinding?: string }> = [
    { title: 'Smart Enter',        body: 'Press Enter after a section header to auto-start a `>> -` item. Press Enter on an empty item to stop the list.' },
    { title: 'Tab to nest',        body: 'Press Tab on any item to promote it one depth deeper - child items move with the parent. Shift+Tab demotes.', keybinding: 'Tab / Shift+Tab' },
    { title: 'Jump between sections', body: 'Jump to the next or previous section header instantly.', keybinding: 'Ctrl+Alt+Down / Ctrl+Alt+Up' },
    { title: 'Toggle note',        body: 'Add or remove an inline `>> > Note` line on the item at the cursor.', keybinding: 'Ctrl+Alt+N' },
    { title: 'Priority colours',   body: 'Add `!`, `!!`, or `!!!` at the start of any item for yellow, amber, or red background highlighting.' },
    { title: 'Due dates',          body: 'Add `@YYYY-MM-DD` to an item to set a due date. The `⚠ N overdue` status bar shows how many are past due - click it to see them all.', command: 'chevron-lists.todayView' },
    { title: 'Tag autocomplete',   body: 'Type `#` in any item to get tag suggestions from the current file, sorted by how often you use them.' },
    { title: 'Section links',      body: 'Type `[[` to autocomplete a link to any section in the file. Hover over a `[[link]]` to preview the section\'s items.' },
    { title: 'Focus Timer',        body: 'Start a configurable Pomodoro-style countdown (default 25 min) in the status bar.', command: 'chevron-lists.startFocusTimer' },
    { title: 'Quick Stats',        body: 'Get an instant one-line summary of the section: items, done %, words, tags, overdue.', command: 'chevron-lists.quickStats' },
    { title: 'Kanban view',        body: 'See all items grouped as Todo, In Progress (starred `*`), and Done in a webview.', command: 'chevron-lists.showKanban' },
    { title: 'Smart Paste',        body: '`CL: Smart Paste` detects whether your clipboard is a numbered list, bullet list, or plain text and converts it automatically.', command: 'chevron-lists.smartPaste' },
    { title: 'Send to Daily Note', body: 'Copy the item at cursor to today\'s daily note under `> Inbox`. Configure the folder in settings.', command: 'chevron-lists.sendToDailyNote' },
    { title: 'Sort by Due Date',   body: 'Reorder items in the current section ascending by `@date` - undated items go last.', command: 'chevron-lists.sortByDueDate' },
    { title: 'Batch Replace',      body: 'Find and replace any text across all items in a section, with a preview count before applying.', command: 'chevron-lists.batchReplaceText' },
    { title: 'Tag Stats',          body: 'Open a webview with every `#tag` in the file, its item count, done count, and a completion % bar.', command: 'chevron-lists.showTagStats' },
    { title: 'Section Growth',     body: 'A bar chart of item count per section - great for seeing where work is concentrated.', command: 'chevron-lists.showSectionGrowth' },
    { title: 'Colour presets',     body: 'Choose from 13 colour presets: default (violet+lime), ocean, forest, midnight, neon, and more.', command: 'chevron-lists.colourTheme' },
    { title: 'Multi-cursor',       body: '`CL: Toggle Done (All Cursors)` and `CL: Set Priority (All Cursors)` act on every active cursor simultaneously.', command: 'chevron-lists.toggleDoneAllCursors' },
    { title: 'Inline calculation', body: 'Add `=2+2` anywhere in an item, then run `CL: Evaluate Expression in Item` to replace it with the result.', command: 'chevron-lists.evaluateExpression' },
    { title: 'Time estimates',     body: 'Add `~2h` or `~30m` to items, then `CL: Show Section Time Estimate` sums them all - great for sprint planning.', command: 'chevron-lists.showSectionTimeEstimate' },
    { title: 'Clone Section',      body: '`CL: Clone Section` duplicates the entire section immediately below with a `(copy)` suffix - perfect for reusable templates.', command: 'chevron-lists.cloneSection' },
    { title: 'Word Count Goals',   body: 'Add `==500` to a section header to set a word goal. Run `CL: Show Word Count Goals` to see progress across every goal section.', command: 'chevron-lists.showWordCountGoals' },
    { title: 'Rich text',          body: 'Use `CL: Bold Text`, `CL: Italic Text`, `CL: Underline Text`, or `CL: Text Transform` to wrap selected text - applies again to unwrap.', command: 'chevron-lists.textTransformPalette' },
];
